server:
  port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   # mybatis配置文件所在路径
  type-aliases-package: com.itbjx.cloud.bean    #所有bean包
  mapper-locations:
    - classpath: mybatis/**/*.xml    # mapper映射文件路径


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/mycloud              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 2000                                  # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/     #注册进eureka中心地址
    instances:
      instance-id: 7001eureka      #微服务的标识id
      prefer-ip-address: true      #标识id上可显示该服务的IP地址