
spring:
  profiles: dev
  application:
    name: mycloud-zull-getway

server:
  port: 5000

zull:
  routes:
    mycloud-provider:
      serviceId: mycloud-provider
      path: /user/**




eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: mycloud-zull3355
    prefer-ip-address: true
