
spring:
  profiles: dev
  application:
    name: mycloud-zull-getway

server:
  port: 3355

zull:
  routes:
    mycloud-provider:
      path: /user/**
      serviceId: mycloud-provider



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: mycloud-zull3355
    prefer-ip-address: true
