
spring:
  profiles: dev
  application:
    name: mycloud-zull-getway

server:
  port: 3355

zull:
  routes:
   # mycloud-provider: /aaa/**
#      serviceId: MYCLOUD-PROVIDER
#      path: /user/**





eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: mycloud-zull3355
    prefer-ip-address: true
