spring: 
  profiles:
    active:
    - dev
--- 


server:
  port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   
  type-aliases-package: com.itbjx.cloud.bean    
  mapper-locations:
    - classpath: mybatis/**/*.xml   


spring: 
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver              
    url: jdbc:mysql://localhost:3306/cloudDB03            
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                       
      max-total: 5                                          
      max-wait-millis: 2000                                  



eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: mycloud-provider8001
    prefer-ip-address: true
 
info:
  app.name: atguigu-microservicecloud-springcloudconfig01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$